### PR TITLE
new flags for austria

### PR DESCRIPTION
**Pull request by Feldgeist**
best
Gregor

### CODE REVIEW

**Comment by zond** [comment]
Ok, so the crown flag is the correct one for Austria-Hungaria in 1901?

**Comment by Feldgeist** [comment]
Hey Martin,

the pull requested flag was used from 1786 – 1918 and was used as naval and war flag (see: http://www.peter-diem.at/bundeswappen.htm at the end of the page)

Here the reasons why I picked this flag and not one of the others I sent you via email:
1)	I found a postcard in the web out of 1914 showing the Austrian-Hungarian flag with the German flag used in droidippy (see http://www.bildpostkarten.uni-osnabrueck.de/displayimage.php?album=88&pos=16). Both flags were used as war flags, so I think this fits for droidippy quiet well.
2)	Everybody who knows Austria connects it with the colors red-white-red.
3)	The Austrian-Hungarian black yellow flag with the double headed eagle looks good, but is very similar to the Russian one and could easily be mixed up with it in the game.

By the way I found out that the different powers in droidippy use different kind of flags. In former days they had different flags for different purposes (naval, war, national, merchant etc.), see for example: https://en.wikipedia.org/wiki/Flags_of_the_Ottoman_Empire 

That means: The actual flag of Turkey used in droidippy is the imperial standard of the Ottoman sultan. During the same period of time the Ottoman empire also used the national flag, that looked different to the sultans standard.
The German and the pull requested Austrian flag were war flags, as well as the english one (https://en.wikipedia.org/wiki/White_Ensign). I like that the flags of the different powers are not completely the same flag-types (for example just merchant flags). That makes droidippy much more diversified.

I hope I could answer your question and that you accept/commit my request!

Best
Gregor

**Comment by zond** [comment]
Thanks for the explanation!

I will certainly accept it, I just need time to sit down and make a new
release :)

Alright, I would be perfectly willing to unify the flag images to a given
type of flag if you want to, you seem much more knowledgeable than me in
the subject matter. If you prefer it the way it is (plus your pull request)
that's also fine.

When I selected them in the beginning it was a combination if stress,
laziness and "this flag was pretty" that made the finall calls :D

**Comment by zond** [comment]
Ok, the new flags are deployed and should be visible in updated Droidippy installs within a few hours :)

**Pull request merged**
